POST http://localhost:3000/atendimentos
Content-Type: application/json

{
  "nome_paciente": "João Silva",
  "data_atendimento": "2026-04-19",
  "tipo_exame": "Admissional",
  "resultado": "APTO",
  "observacoes": "Sem restrições"
}